### Import Libraries & Read File

In [1]:
import pandas as pd

In [4]:
parsed = pd.read_csv('./data/parsed_data.csv')
info = pd.read_csv('./data/data.info')
info = info.rename(columns={"transcript_position": "position"})

df = pd.merge(parsed,info,on=['transcript_id', 'position'] ,how='left')

#### Mean

In [7]:
mean_ds = df.groupby(["gene_id", "transcript_id", "position"]).mean().reset_index()
mean_ds

,gene_id,transcript_id,position,dwell_1,std_1,mean_1,dwell_2,std_2,mean_2,dwell_3,std_3,mean_3,label
0,ENSG00000000003,ENST00000373020,512,0.007247,2.359500,86.795000,0.011177,2.496500,97.965000,0.008500,1.588750,92.330000,0.0
1,ENSG00000000003,ENST00000373020,689,0.009868,1.972857,102.495238,0.007332,2.551905,97.928571,0.006917,2.198571,89.385714,0.0
2,ENSG00000000003,ENST00000373020,823,0.007456,2.078095,86.904762,0.006193,1.912857,93.680952,0.007296,2.306667,88.176190,0.0
3,ENSG00000000003,ENST00000373020,830,0.007765,2.834000,86.765000,0.007522,3.192500,93.075000,0.005923,2.020500,80.110000,0.0
4,ENSG00000000003,ENST00000373020,849,0.006785,2.926667,86.923810,0.007727,2.782381,92.504762,0.008596,1.924286,84.657143,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,0.007506,3.685833,109.766667,0.007801,6.736167,118.050000,0.006870,2.844667,80.915000,1.0
121834,ENSG00000284707,ENST00000641784,3142,0.008712,3.650164,105.637705,0.007614,8.877377,119.721311,0.005795,3.218689,77.859016,0.0
121835,ENSG00000284707,ENST00000641784,3224,0.008452,3.807667,118.583333,0.008247,4.507167,124.466667,0.006606,3.443833,91.126667,1.0
121836,ENSG00000284707,ENST00000641784,3243,0.008700,7.686719,122.812500,0.007648,2.998125,97.346875,0.005190,2.203750,88.439063,0.0
121837,ENSG00000284707,ENST00000641784,3266,0.005972,1.874516,94.209677,0.006831,2.194032,99.730645,0.006503,1.977742,92.453226,0.0

In [8]:
nuc = df[["gene_id", "transcript_id", "position", "nucleotide"]].groupby(["gene_id", "transcript_id", "position"])["nucleotide"].unique().reset_index()
nuc.nucleotide = nuc.nucleotide.apply(lambda x: x[0])
nuc

                gene_id    transcript_id  position nucleotide
0       ENSG00000000003  ENST00000373020       512    ATAACTC
1       ENSG00000000003  ENST00000373020       689    TAAACAA
2       ENSG00000000003  ENST00000373020       823    ATAACAA
3       ENSG00000000003  ENST00000373020       830    ATAACCA
4       ENSG00000000003  ENST00000373020       849    GTAACCC
...                 ...              ...       ...        ...
121833  ENSG00000284707  ENST00000641784      3122    CTGACCC
121834  ENSG00000284707  ENST00000641784      3142    CTGACCC
121835  ENSG00000284707  ENST00000641784      3224    GGGACTG
121836  ENSG00000284707  ENST00000641784      3243    GGAACAA
121837  ENSG00000284707  ENST00000641784      3266    CTAACTT

[121838 rows x 4 columns]

In [10]:
mean_ds = mean_ds.merge(nuc)
mean_ds

,gene_id,transcript_id,position,dwell_1,std_1,mean_1,dwell_2,std_2,mean_2,dwell_3,std_3,mean_3,label,nucleotide
0,ENSG00000000003,ENST00000373020,512,0.007247,2.359500,86.795000,0.011177,2.496500,97.965000,0.008500,1.588750,92.330000,0.0,ATAACTC
1,ENSG00000000003,ENST00000373020,689,0.009868,1.972857,102.495238,0.007332,2.551905,97.928571,0.006917,2.198571,89.385714,0.0,TAAACAA
2,ENSG00000000003,ENST00000373020,823,0.007456,2.078095,86.904762,0.006193,1.912857,93.680952,0.007296,2.306667,88.176190,0.0,ATAACAA
3,ENSG00000000003,ENST00000373020,830,0.007765,2.834000,86.765000,0.007522,3.192500,93.075000,0.005923,2.020500,80.110000,0.0,ATAACCA
4,ENSG00000000003,ENST00000373020,849,0.006785,2.926667,86.923810,0.007727,2.782381,92.504762,0.008596,1.924286,84.657143,0.0,GTAACCC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,0.007506,3.685833,109.766667,0.007801,6.736167,118.050000,0.006870,2.844667,80.915000,1.0,CTGACCC
121834,ENSG00000284707,ENST00000641784,3142,0.008712,3.650164,105.637705,0.007614,8.877377,119.721311,0.005795,3.218689,77.859016,0.0,CTGACCC
121835,ENSG00000284707,ENST00000641784,3224,0.008452,3.807667,118.583333,0.008247,4.507167,124.466667,0.006606,3.443833,91.126667,1.0,GGGACTG
121836,ENSG00000284707,ENST00000641784,3243,0.008700,7.686719,122.812500,0.007648,2.998125,97.346875,0.005190,2.203750,88.439063,0.0,GGAACAA
121837,ENSG00000284707,ENST00000641784,3266,0.005972,1.874516,94.209677,0.006831,2.194032,99.730645,0.006503,1.977742,92.453226,0.0,CTAACTT

In [22]:
mean_ds.to_csv("./data/mean_dataset.csv", index=False)

#### Median

In [12]:
compressed_df = df.groupby(["gene_id", "transcript_id", "position"]).median().reset_index()
compressed_df

,gene_id,transcript_id,position,dwell_1,std_1,mean_1,dwell_2,std_2,mean_2,dwell_3,std_3,mean_3,label
0,ENSG00000000003,ENST00000373020,512,0.005990,2.325,87.05,0.007735,2.375,98.05,0.00687,1.570,92.55,0.0
1,ENSG00000000003,ENST00000373020,689,0.007640,1.980,103.00,0.006420,2.430,98.70,0.00573,2.190,89.60,0.0
2,ENSG00000000003,ENST00000373020,823,0.006310,2.100,87.20,0.005400,1.900,93.40,0.00631,2.250,88.20,0.0
3,ENSG00000000003,ENST00000373020,830,0.006410,2.585,86.85,0.005645,3.180,93.80,0.00496,1.820,80.00,0.0
4,ENSG00000000003,ENST00000373020,849,0.005980,2.290,86.50,0.006930,2.710,92.30,0.00664,1.830,84.40,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,0.005475,3.270,111.00,0.007165,6.365,117.00,0.00564,2.525,81.15,1.0
121834,ENSG00000284707,ENST00000641784,3142,0.007640,3.470,105.00,0.006100,8.880,120.00,0.00498,3.040,78.00,0.0
121835,ENSG00000284707,ENST00000641784,3224,0.006970,3.700,119.00,0.006310,4.420,125.00,0.00559,3.045,91.45,1.0
121836,ENSG00000284707,ENST00000641784,3243,0.007350,7.680,124.00,0.006580,2.675,97.60,0.00466,2.130,88.70,0.0
121837,ENSG00000284707,ENST00000641784,3266,0.005065,1.760,94.80,0.005785,2.170,99.75,0.00578,1.825,92.65,0.0

In [13]:
temp = df[["gene_id", "transcript_id", "position", "nucleotide"]].groupby(["gene_id", "transcript_id", "position"])["nucleotide"].unique().reset_index()
temp.nucleotide = temp.nucleotide.apply(lambda x: x[0])
temp

                gene_id    transcript_id  position nucleotide
0       ENSG00000000003  ENST00000373020       512    ATAACTC
1       ENSG00000000003  ENST00000373020       689    TAAACAA
2       ENSG00000000003  ENST00000373020       823    ATAACAA
3       ENSG00000000003  ENST00000373020       830    ATAACCA
4       ENSG00000000003  ENST00000373020       849    GTAACCC
...                 ...              ...       ...        ...
121833  ENSG00000284707  ENST00000641784      3122    CTGACCC
121834  ENSG00000284707  ENST00000641784      3142    CTGACCC
121835  ENSG00000284707  ENST00000641784      3224    GGGACTG
121836  ENSG00000284707  ENST00000641784      3243    GGAACAA
121837  ENSG00000284707  ENST00000641784      3266    CTAACTT

[121838 rows x 4 columns]

In [14]:
compressed_df = compressed_df.merge(temp)
compressed_df

,gene_id,transcript_id,position,dwell_1,std_1,mean_1,dwell_2,std_2,mean_2,dwell_3,std_3,mean_3,label,nucleotide
0,ENSG00000000003,ENST00000373020,512,0.005990,2.325,87.05,0.007735,2.375,98.05,0.00687,1.570,92.55,0.0,ATAACTC
1,ENSG00000000003,ENST00000373020,689,0.007640,1.980,103.00,0.006420,2.430,98.70,0.00573,2.190,89.60,0.0,TAAACAA
2,ENSG00000000003,ENST00000373020,823,0.006310,2.100,87.20,0.005400,1.900,93.40,0.00631,2.250,88.20,0.0,ATAACAA
3,ENSG00000000003,ENST00000373020,830,0.006410,2.585,86.85,0.005645,3.180,93.80,0.00496,1.820,80.00,0.0,ATAACCA
4,ENSG00000000003,ENST00000373020,849,0.005980,2.290,86.50,0.006930,2.710,92.30,0.00664,1.830,84.40,0.0,GTAACCC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,0.005475,3.270,111.00,0.007165,6.365,117.00,0.00564,2.525,81.15,1.0,CTGACCC
121834,ENSG00000284707,ENST00000641784,3142,0.007640,3.470,105.00,0.006100,8.880,120.00,0.00498,3.040,78.00,0.0,CTGACCC
121835,ENSG00000284707,ENST00000641784,3224,0.006970,3.700,119.00,0.006310,4.420,125.00,0.00559,3.045,91.45,1.0,GGGACTG
121836,ENSG00000284707,ENST00000641784,3243,0.007350,7.680,124.00,0.006580,2.675,97.60,0.00466,2.130,88.70,0.0,GGAACAA
121837,ENSG00000284707,ENST00000641784,3266,0.005065,1.760,94.80,0.005785,2.170,99.75,0.00578,1.825,92.65,0.0,CTAACTT

In [23]:
compressed_df.to_csv("./data/median_dataset.csv", index=False)

#### Min-Max

In [16]:
min_dataset = df.groupby(['gene_id', 'transcript_id', 'position']).min().reset_index()
max_dataset = df.groupby(['gene_id', 'transcript_id', 'position']).max().reset_index()

In [17]:
max_dataset = max_dataset.rename(columns = {"dwell_1": "dwell_1_max",
                    "std_1": "std_1_max",
                    "mean_1": "mean_1_max",
                    "dwell_2": "dwell_2_max",
                    "std_2": "std_2_max",
                    "mean_2": "mean_2_max",
                    "dwell_3": "dwell_3_max",
                    "std_3": "std_3_max",
                    "mean_3": "mean_3_max"})

In [18]:
minmax_data = pd.merge(min_dataset,max_dataset,on=['gene_id', 'transcript_id', 'position', "nucleotide", 'label'] ,how='left')

In [19]:
column_to_move = minmax_data.pop("label")
minmax_data.insert(22, "label", column_to_move)

In [20]:
minmax_data

,gene_id,transcript_id,position,nucleotide,dwell_1,std_1,mean_1,dwell_2,std_2,mean_2,...,dwell_1_max,std_1_max,mean_1_max,dwell_2_max,std_2_max,mean_2_max,dwell_3_max,std_3_max,mean_3_max,label
0,ENSG00000000003,ENST00000373020,512,ATAACTC,0.00266,1.28,83.5,0.00232,1.48,94.7,...,0.0169,3.91,91.2,0.0461,4.34,101.0,0.0219,2.18,94.5,0
1,ENSG00000000003,ENST00000373020,689,TAAACAA,0.00232,1.16,96.5,0.00232,1.42,91.1,...,0.0279,2.78,106.0,0.0179,4.12,102.0,0.0175,4.15,93.5,0
2,ENSG00000000003,ENST00000373020,823,ATAACAA,0.00299,1.17,81.4,0.00283,1.00,88.8,...,0.0196,3.45,89.9,0.0125,2.78,98.0,0.0153,3.60,93.1,0
3,ENSG00000000003,ENST00000373020,830,ATAACCA,0.00266,1.56,82.6,0.00232,1.60,84.3,...,0.0226,5.86,91.9,0.0196,5.24,101.0,0.0154,3.44,83.8,0
4,ENSG00000000003,ENST00000373020,849,GTAACCC,0.00332,1.35,83.8,0.00232,1.80,87.7,...,0.0181,10.50,93.5,0.0219,5.16,97.7,0.0185,3.80,90.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121833,ENSG00000284707,ENST00000641784,3122,CTGACCC,0.00232,1.86,94.7,0.00232,3.12,110.0,...,0.0438,9.28,117.0,0.0229,15.40,126.0,0.0236,5.64,84.7,1
121834,ENSG00000284707,ENST00000641784,3142,CTGACCC,0.00232,1.74,98.6,0.00232,2.47,109.0,...,0.0259,11.60,113.0,0.0262,14.70,130.0,0.0152,10.10,83.5,0
121835,ENSG00000284707,ENST00000641784,3224,GGGACTG,0.00232,1.66,114.0,0.00232,1.78,116.0,...,0.0266,5.96,124.0,0.0257,9.97,132.0,0.0199,8.95,97.0,1
121836,ENSG00000284707,ENST00000641784,3243,GGAACAA,0.00204,2.92,107.0,0.00232,1.63,91.6,...,0.0372,12.20,134.0,0.0222,9.40,105.0,0.0136,5.43,97.4,0
121837,ENSG00000284707,ENST00000641784,3266,CTAACTT,0.00232,1.02,86.2,0.00232,1.42,89.8,...,0.0187,3.19,99.7,0.0203,3.40,103.0,0.0147,4.36,96.0,0

In [24]:
minmax_data.to_csv('./data/minmax_dataset.csv', header= True, index=False)